#!/bin/bash

# this script is autogenerated by 'ant startscripts'
# it starts a LAS2peer node providing the service 'i5.las2peer.services.ocd.ServiceClass' of this project
# pls execute it from the root folder of your deployment, e. g. ./bin/start_network.sh

java -cp "lib/*:service/*" i5.las2peer.tools.L2pNodeLauncher -p 9015 --bootstrap 192.168.178.44:9011 --bootstrap 192.168.178.44:9013 --bootstrap 192.168.178.44:9020 uploadStartupDirectory\(\'etc/startup\'\) startService\(\'i5.las2peer.services.ocd.ServiceClass@1.0\'\) interactive

